# .goreleaser.yml
before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
    goarm:
      - 6
    flags:
      - -trimpath
    ldflags:
      - -s -w
    ignore:
      - goos: darwin
        goarch: 386

replacements:
  darwin: Darwin
  linux: Linux
  windows: Windows
  386: i386
  amd64: x86_64

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-{{ .Commit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'