# .goreleaser.yml
before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
    goarm:
      - 6
    flags:
      - -trimpath
    ldflags:
      - -s -w
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: binary

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-{{ .Commit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'