# .goreleaser.yml
before:
  hooks:
    - mkdir -p internal
    - go mod tidy
    - go generate ./...
    - go install github.com/akavel/rsrc@latest
    - which rsrc
    - rsrc -ico ./icon.ico -o ./ico.syso

builds:
  - id: nowin
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
    flags:
      - -trimpath
    ldflags:
      - -s -w
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: '386'
  - id: win
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: binary
    builds:
      - win
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: binary
  - id: nowin
    builds:
      - nowin
      - win
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-{{ .Commit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'