name: Build and Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+$'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build binaries
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        run: |
          for file in dist/*; do
            if [[ -f "$file" ]]; then
              echo "Uploading $file"
              curl \
                --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                --header "Content-Type: $(file -b --mime-type $file)" \
                --data-binary @"$file" \
                "${{ github.event.release.upload_url }}?name=$(basename $file)"
            fi
          done